//
//  SeasonsModels.swift
//  WhistApp
//
//  Created by Christian Graver on 07/12/2020.
//  Copyright (c) 2020 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

enum Seasons {
    enum Request { }
    enum Response { }
    enum DisplayData { }
}

extension Seasons.Request {
    struct ViewCreated {}
    struct CreateSeason {
        var name: String
        var year: Int
    }
}

extension Seasons.Response {
    
}

extension Seasons.DisplayData {
    struct Season {
        var name: String
        var year: Int
    }
}
