//
//  SeasonsRouter.swift
//  WhistApp
//
//  Created by Christian Graver on 07/12/2020.
//  Copyright (c) 2020 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol SeasonsRoutingLogic {
}

protocol SeasonsDataPassing {
    var dataStore: SeasonsDataStore? { get }
}

class SeasonsRouter: NSObject, SeasonsDataPassing {
    weak var viewController: SeasonsViewController?
    var dataStore: SeasonsDataStore?
}

extension SeasonsRouter: SeasonsRoutingLogic {
    
}
