//
//  SeasonsRouter.swift
//  WhistApp
//
//  Created by Christian Graver on 07/12/2020.
//  Copyright (c) 2020 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol SeasonsRoutingLogic {
    func seasonCellSelected(index: Int)
}

protocol SeasonsDataPassing {
    var dataStore: SeasonsDataStore? { get }
}

class SeasonsRouter: NSObject, SeasonsDataPassing {
    weak var viewController: SeasonsViewController?
    var dataStore: SeasonsDataStore?
}

extension SeasonsRouter: SeasonsRoutingLogic {
    func seasonCellSelected(index: Int) {
        guard let season = dataStore?.seasons[safe: index] else { return }
        let matchesVC = MatchesViewController.instantiate()
        if var dataStore = matchesVC.router?.dataStore {
            passDataToMatches(season: season, destination: &dataStore)
        }
        viewController?.navigationController?.pushViewController(matchesVC, animated: true)
    }
    
    // MARK: Passing data
    private func passDataToMatches(season: Season, destination: inout MatchesDataStore) {
        destination.season = season
    }
    
}
