//
//  SeasonsPresenter.swift
//  WhistApp
//
//  Created by Christian Graver on 07/12/2020.
//  Copyright (c) 2020 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol SeasonsPresentationLogic {
    func presentSeasons(response: [Season])
    func presentNewSeason(response: Season)
}

class SeasonsPresenter {
    weak var viewController: SeasonsDisplayLogic?
}

extension SeasonsPresenter: SeasonsPresentationLogic {
    func presentNewSeason(response: Season) {
        let seasonVM = Seasons.DisplayData.Season(name: response.name,
                                                  year: response.year)
        viewController?.displayNewSeason(viewModel: seasonVM)
        
    }
    
    func presentSeasons(response: [Season]) {
        let seasonVMs: [Seasons.DisplayData.Season] = response.map { (season) -> Seasons.DisplayData.Season in
            return Seasons.DisplayData.Season(name: season.name,
                                              year: season.year)
        }
        viewController?.displaySeasons(viewModel: seasonVMs)
    }
}
