//
//  MatchesRouter.swift
//  WhistApp
//
//  Created by Christian Graver on 14/01/2021.
//  Copyright (c) 2021 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol MatchesRoutingLogic {
    func matchCellSelected(index: Int)
}

protocol MatchesDataPassing {
    var dataStore: MatchesDataStore? { get }
}

class MatchesRouter: NSObject, MatchesDataPassing {
    weak var viewController: MatchesViewController?
    var dataStore: MatchesDataStore?
}

extension MatchesRouter: MatchesRoutingLogic {
    func matchCellSelected(index: Int) {
        
    }
}
