//
//  MatchesPresenter.swift
//  WhistApp
//
//  Created by Christian Graver on 14/01/2021.
//  Copyright (c) 2021 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

protocol MatchesPresentationLogic {
    func presentMatches(response: [Match])
}

class MatchesPresenter {
    weak var viewController: MatchesDisplayLogic?
}

extension MatchesPresenter: MatchesPresentationLogic {
    func presentMatches(response: [Match]) {
        let matchVMs: [Matches.DisplayData.Match] = response.map { (match) -> Matches.DisplayData.Match in
            return Matches.DisplayData.Match(name: match.name,
                                             dateString: Formatters.humanDateFormat.string(from: match.date))
        }
        viewController?.displayMatches(viewModel: matchVMs)
    }
}
