//
//  AddGameRouter.swift
//  WhistApp
//
//  Created by Christian Graver on 17/01/2021.
//  Copyright (c) 2021 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol AddGameRoutingLogic {
}

protocol AddGameDataPassing {
    var dataStore: AddGameDataStore? { get }
}

class AddGameRouter: NSObject, AddGameDataPassing {
    weak var viewController: AddGameViewController?
    var dataStore: AddGameDataStore?
}

extension AddGameRouter: AddGameRoutingLogic {
    
}
