//
//  MatchGamesRouter.swift
//  WhistApp
//
//  Created by Christian Graver on 17/01/2021.
//  Copyright (c) 2021 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

@objc protocol MatchGamesRoutingLogic {
    func addGamePressed()
}

protocol MatchGamesDataPassing {
    var dataStore: MatchGamesDataStore? { get }
}

class MatchGamesRouter: NSObject, MatchGamesDataPassing {
    weak var viewController: MatchGamesViewController?
    var dataStore: MatchGamesDataStore?
}

extension MatchGamesRouter: MatchGamesRoutingLogic {
    func addGamePressed() {
        let addGameVC = AddGameViewController.instantiate()
        addGameVC.modalPresentationStyle = .overCurrentContext
        viewController?.navigationController?.present(addGameVC, animated: true)
    }
}
