//
//  MatchGamesModels.swift
//  WhistApp
//
//  Created by Christian Graver on 17/01/2021.
//  Copyright (c) 2021 Gravr. All rights reserved.
//
//  This file was generated by the Daman Clean Swift Xcode Templates
//  with inspiration from http://clean-swift.com
//

import UIKit

enum MatchGames {
    enum Request { }
    enum Response { }
    enum DisplayData { }
}

extension MatchGames.Request {
    
}

extension MatchGames.Response {
    
}

extension MatchGames.DisplayData {
    
}
